[package]
name = "ac-power"
version = "0.1.0"
edition = "2018"

[dependencies]
fixed = "2.0.0-alpha.12"
idsp = "0.11.0"
heapless = "0.7.16"

[dev-dependencies]
plotlib = "0.5.1"  # used to plot results for debugging
approx = "0.5.1"