[package]
name = "ac-power"
version = "0.1.0"
edition = "2018"

[dependencies]
fixed = {git="https://gitlab.com/tspiteri/fixed.git", tag="v2.0.0-alpha.12"}
idsp = "0.11.0"

[dev-dependencies]
plotlib = "0.5.1"  # used to plot results for debugging
approx = "0.5.1"